---
- name: Install PostgreSQL
  ansible.builtin.apt:
    name:
      - postgresql-{{ postgresql_version }}
      - postgresql-client-{{ postgresql_version }}
      - postgresql-contrib-{{ postgresql_version }}
    state: present
    update_cache: true


- name: Ensure PostgreSQL service is started and enabled
  ansible.builtin.systemd:
    name: postgresql
    state: "{{ postgresql_service_state }}"
    enabled: "{{ postgresql_service_enabled }}"

- name: Check if ufw is installed
  ansible.builtin.command: which ufw
  register: ufw_check
  changed_when: false
  failed_when: false

- name: Open port 5432 via ufw
  community.general.ufw:
    rule: allow
    port: "{{ postgresql_port }}"
    proto: tcp
  when: ufw_check.rc == 0